export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const RESET_AUTH_ERROR = "RESET_AUTH_ERROR";

export const FETCH_USER_ROLES_SUCCESS = "FETCH_USER_ROLES_SUCCESS";
export const FETCH_DEPARTMENTS_SUCCESS = "FETCH_DEPARTMENTS_SUCCESS";
export const FETCH_PROGRAMS_SUCCESS = "FETCH_PROGRAMS_SUCCESS";

export const LOGIN_USER_PENDING = "LOGIN_USER_PENDING";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILED = "LOGIN_USER_FAILED";

export const RESET_PASSWORD_PENDING = "RESET_PASSWORD_PENDING";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAILED = "RESET_PASSWORD_FAILED";

export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_USER_PENDING = "UPDATE_USER_PENDING";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAILED = "UPDATE_USER_FAILED";

export const FETCH_AVATAR_IMAGE = "FETCH_AVATAR_IMAGE";
export const FETCH_AVATAR_IMAGE_PENDING = "FETCH_AVATAR_IMAGE_PENDING";
export const FETCH_AVATAR_IMAGE_SUCCESS = "FETCH_AVATAR_IMAGE_SUCCESS";
export const FETCH_AVATAR_IMAGE_FAILED = "FETCH_AVATAR_IMAGE_FAILED";

export const UPLOAD_AVATAR = "UPLOAD_AVATAR";
export const UPLOAD_AVATAR_PENDING = "UPLOAD_AVATAR_PENDING";
export const UPLOAD_AVATAR_SUCCESS = "UPLOAD_AVATAR_SUCCESS";
export const UPLOAD_AVATAR_FAILED = "UPLOAD_AVATAR_FAILED";

export const CHANGE_PASSWORD = "CHANGE_PASSWORD";

export const REGISTER_USER_PENDING = "REGISTER_USER_PENDING";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILED = "REGISTER_USER_FAILED";

export const FETCH_COURSES_PENDING = "FETCH_COURSES_PENDING";
export const FETCH_COURSES_SUCCESS = "FETCH_COURSES_SUCCESS";
export const FETCH_COURSES_FAILED = "FETCH_COURSES_FAILED";

export const CREATE_COURSE_PENDING = "CREATE_COURSE_PENDING";
export const CREATE_COURSE_SUCCESS = "CREATE_COURSE_SUCCESS";
export const CREATE_COURSE_FAILED = "CREATE_COURSE_FAILED";

export const DELETE_COURSE_PENDING = "DELETE_COURSE_PENDING";
export const DELETE_COURSE_SUCCESS = "DELETE_COURSE_SUCCESS";
export const DELETE_COURSE_FAILED = "DELETE_COURSE_FAILED";

export const FETCH_ENROLLED_COURSES_PENDING = "FETCH_ENROLLED_COURSES_PENDING";
export const FETCH_ENROLLED_COURSES_SUCCESS = "FETCH_ENROLLED_COURSES_SUCCESS";
export const FETCH_ENROLLED_COURSES_FAILED = "FETCH_ENROLLED_COURSES_FAILED";

export const FETCH_AVAILABLE_COURSES_PENDING =
  "FETCH_AVAILABLE_COURSES_PENDING";
export const FETCH_AVAILABLE_COURSES_SUCCESS =
  "FETCH_AVAILABLE_COURSES_SUCCESS";
export const FETCH_AVAILABLE_COURSES_FAILED = "FETCH_AVAILABLE_COURSES_FAILED";

export const GET_TO_APPROVE_COURSES_PENDING = "GET_TO_APPROVE_COURSES_PENDING";
export const GET_TO_APPROVE_COURSES_SUCCESS = "GET_TO_APPROVE_COURSES_SUCCESS";
export const GET_TO_APPROVE_COURSES_FAILED = "GET_TO_APPROVE_COURSES_FAILED";

export const ENROLL_COURSE_PENDING = "ENROLL_COURSE_PENDING";
export const ENROLL_COURSE_SUCCESS = "ENROLL_COURSE_SUCCESS";
export const ENROLL_COURSE_FAILED = "ENROLL_COURSE_FAILED";

export const APPROVE_ENROLLMENT_PENDING = "APPROVE_ENROLLMENT_PENDING";
export const APPROVE_ENROLLMENT_SUCCESS = "APPROVE_ENROLLMENT_SUCCESS";
export const APPROVE_ENROLLMENT_FAILED = "APPROVE_ENROLLMENT_FAILED";

export const FETCH_DISCUSSION_THREADS_PENDING =
  "FETCH_DISCUSSION_THREADS_PENDING";
export const FETCH_DISCUSSION_THREADS_SUCCESS =
  "FETCH_DISCUSSION_THREADS_SUCCESS";
export const FETCH_DISCUSSION_THREADS_FAILED =
  "FETCH_DISCUSSION_THREADS_FAILED";

export const CREATE_DISCUSSION_THREAD_PENDING =
  "CREATE_DISCUSSION_THREAD_PENDING";
export const CREATE_DISCUSSION_THREAD_SUCCESS =
  "CREATE_DISCUSSION_THREAD_SUCCESS";
export const CREATE_DISCUSSION_THREAD_FAILED =
  "CREATE_DISCUSSION_THREAD_FAILED";

export const UPDATE_DISCUSSION_THREAD_PENDING =
  "UPDATE_DISCUSSION_THREAD_PENDING";
export const UPDATE_DISCUSSION_THREAD_SUCCESS =
  "UPDATE_DISCUSSION_THREAD_SUCCESS";
export const UPDATE_DISCUSSION_THREAD_FAILED =
  "UPDATE_DISCUSSION_THREAD_FAILED";
export const SET_DISCUSSION_THREAD_EDIT_ID = "SET_DISCUSSION_THREAD_EDIT_ID";
